version: 0.2
phases:
  #install:
    #runtime-versions:
      #java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR, EKS
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
     #- sed -i 's@CONTAINER_IMAGE@'"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"'@' was.yaml
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - export LATEST_BUILD=$(aws codebuild list-builds | jq '.ids[0]')
      - export LATEST_BUILD_NUMBER=$(aws codebuild batch-get-builds --ids ${LATEST_BUILD:1:-1} | jq '.builds[0].buildNumber')
      - export LATEST_BUILD_NUMBER=$((INT=$((LATEST_BUILD_NUMBER))+1))
     #- aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME
  build:
    commands:
      - echo Build started on 'date'
      - echo Building the Docker image...
        #- mvn clean package
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$LATEST_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$LATEST_BUILD_NUMBER
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$LATEST_BUILD_NUMBER
     #- kubectl apply -f was.yaml 
cache:
  paths:
    - '/root/.m2/**/*'
