apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - image: CONTAINER_IMAGE
        imagePullPolicy: Always
        name: was
        ports:
        - containerPort: 8080
