apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - image: 164134553042.dkr.ecr.ap-northeast-2.amazonaws.com/ana-test-ecr-repo:latest
        imagePullPolicy: Always
        name: was
        ports:
        - containerPort: 8080
